import express from 'express';
import engine from 'express-handlebars';
import path from 'path';
import session from 'express-session';
import methodOverride from 'method-override';
import flash from 'connect-flash';
import passport from 'passport';
import morgan from 'morgan';
import MongoStore from 'connect-mongo';
import config from './config';
const app=express();
app.set();
export default app;
